// src/routes/art/index.svelte
<h1 class="text-secondary text-base">some pixely doodles</h1>

<hr />

<div class="md:-mt-12">
  <img
    src="/assets/store-day.png"
    alt="A peaceful little bookstore"
    class="w-full only-light pixel aspect-square"
  />
  <img
    src="/assets/store-night.png"
    alt="A peaceful little bookstore"
    class="w-full only-dark pixel aspect-square"
  />
</div>

// app/routes/art.tsx
import { pageMeta } from '~/lib/page-meta';
import type { Route } from './+types/art';

export function meta({ location }: Route.MetaArgs) {
  return pageMeta({ title: 'art', pathname: location.pathname });
}

export default function ArtPage() {
  return (
    <div className="px-8 py-8 md:px-12 lg:px-20">
      <div className="max-w-2xl 2xl:max-w-3xl m-auto">
        <h1 className="text-secondary text-base">some pixely doodles</h1>

        <hr />

        <div className="md:-mt-12">
          <img
            src="/assets/store-day.png"
            alt="A peaceful little bookstore"
            className="w-full dark:hidden pixel aspect-square"
          />
          <img
            src="/assets/store-night.png"
            alt="A peaceful little bookstore"
            className="w-full hidden dark:block pixel aspect-square"
          />
        </div>
      </div>
    </div>
  );
}
